---
name: Spear PHPUnit Runner
description: A GitHub action to run PHPUnit and record test coverage
branding:
  icon: check-circle
  color: green
inputs:
  credHelperConfig:
    description: Auth section to add to docker.json
    required: true
    
runs:
  using: composite
  steps:
    - id: configure-docker-ecr-helper
      run: |
        set -ex
        apt-get install -y amazon-ecr-credential-helper
        CRED_HELPER_CONFIG="${{ inputs.credHelperConfig }}"
        ECR_OUTPUT="{ \"auths\": {}, \n\"credHelpers\": { \n${CRED_HELPER_CONFIG} }}"
        mkdir -p ~/.docker
        echo "${ECR_OUTPUT}"
        
        echo ${ECR_OUTPUT} > ~/.docker/config.json
      shell: bash